name: Grade Assignment

on: [push]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 11
        uses: actions/setup-java@v6
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and test with Maven
        run: mvn -B test --file pom.xml
